export const STARTING_LOCATIONS: string[] = [
  "A rain-slicked Berlin alley, 1989",
  "A forgotten ward in a New Orleans hospital",
  "A secluded cabin in the Swedish wilderness",
  "A neon-drenched Tokyo backstreet",
  "A crumbling psychiatric hospital in post-Soviet Estonia",
  "The last late-night subway car in Seoul",
  "A lavish but empty penthouse in Dubai",
  "A flooded bayou village in Louisiana",
  "An ancient, dusty library in Alexandria",
  "A fog-bound fishing trawler in the North Sea",
  "A sterile corporate research lab after hours",
  "A makeshift refugee camp on a forgotten border",
  "An opulent, decaying opera house in Vienna",
  "A sun-scorched motel in the Mojave Desert",
  "The catacombs beneath a Parisian cathedral",
  "An abandoned Cold War listening post in Teufelsberg",
  "The derelict 'Wonderland' amusement park outside Beijing",
  "A sterile cryogenics facility during a power failure",
  "The last video rental store in a dying suburban town",
  "A fog-shrouded oil rig in the North Atlantic",
  "Inside a replica 1950s town built for nuclear tests",
  "A forgotten station in the Moscow Metro-2 system",
  "The bone-white salt flats of Uyuni, Bolivia, at midnight",
  "A sweatshop in Dhaka, Bangladesh, during a blackout",
  "The crumbling art deco lobby of the Grand Hotel in Beira, Mozambique",
  "A research station in the Antarctic during polar night",
  "The claustrophobic tunnels of Củ Chi, Vietnam",
  "A hauntingly quiet cruise ship adrift at sea",
  "The ghost city of Pripyat, near Chernobyl",
  "A centuries-old monastery carved into a cliffside",
  "The sprawling, chaotic market of Lagos, Nigeria",
  "A decommissioned nuclear submarine base in Murmansk",
  "The eerily silent, abandoned island of Hashima, Japan",
  "A high-stakes poker game in a Macau casino's backroom",
  "The waterlogged streets of a sinking Venice",
  "An illegal organ harvesting clinic in a São Paulo favela",
  "A long-haul sleeper train crossing Siberia",
  "The skeletal remains of the Aral Sea's fishing fleet",
  "A smoke-filled jazz club in 1940s Harlem",
  "The heavily guarded Demilitarized Zone between the Koreas",
  "A remote weather station in the Scottish Highlands",
  "An abandoned diamond mine in Kimberley, South Africa",
  "The labyrinthine alleys of the Fez medina, Morocco",
  "A family reunion in a decaying ancestral mansion",
  "The sterile environment of a deep space simulation habitat",
  "A half-finished luxury resort on a bankrupt Spanish coast",
  "The tense quiet of a Colombian coffee farm in FARC territory",
  "A crowded pilgrimage site in Varanasi, India",
  "The frozen ghost town of Pyramiden in Svalbard",
  "An all-night truck stop diner on a desolate highway",
  "A clandestine data haven in the Sealand fortress",
  "The endless, identical halls of a suburban office park",
  "A once-grand theater now showing only snuff films",
  "The precarious cliff dwellings of the Anasazi",
  "A luxury doomsday bunker, sealed from the outside",
  "The tense atmosphere of a border checkpoint in Tijuana",
  "An old lighthouse during a Category 5 hurricane",
  "A surrealist art gallery after closing time",
  "The overgrown ruins of a colonial palace in the Congo",
  "A maximum-security prison during a riot",
  "The back rooms of a traveling circus",
  "A forgotten Cold War-era spy's dead drop location",
  "The eerie silence of a town under a volcanic ash cloud",
  "A floating slum on the Tonlé Sap lake in Cambodia",
  "An underground, illegal rave in a London sewer",
  "The perfectly preserved home of a recently deceased hoarder",
  "A remote ayahuasca retreat in the Peruvian Amazon",
  "The sterile waiting room of a controversial fertility clinic",
  "A desolate stretch of Australia's Nullarbor Plain",
  "The final night of the notorious Kowloon Walled City",
  "A black site prison where you are the new interrogator",
  "The quiet desperation of a Rust Belt factory town",
  "A secret meeting of a cult in the Swiss Alps",
  "The chaotic floor of the New York Stock Exchange",
  "A lonely fire lookout tower in a drought-stricken forest",
  "The opulent, stifling interior of the Orient Express",
  "A genetics lab working on de-extinction",
  "The somber grounds of the Killing Fields in Cambodia",
  "A vast, automated shipping warehouse",
  "The grimy engine room of a colossal container ship",
  "A memory-palace constructed for a retired spy",
  "The paranoid set of a Cold War propaganda film",
  "A tense family dinner on a remote Icelandic farm",
  "The endless cornfields of rural Nebraska",
  "A high-frequency trading firm during a market crash",
  "The abandoned metro tunnels beneath Cincinnati",
  "A roadside memorial on a lonely stretch of highway",
  "A half-excavated archeological dig of a new, unknown civilization",
  "The quiet, manicured lawns of a gated community",
  "A puppet workshop filled with uncanny creations",
  "The last payphone in a city of millions",
  "A struggling funeral home in a town with no deaths",
  "The off-season lobby of a grand hotel from 'The Shining'",
  "A numbers station broadcasting from a Cuban jungle",
  "The sterile cleanroom of a semiconductor factory",
  "A community fallout shelter, decades after the war",
  "The tense green room of a failing late-night talk show",
  "A boat locked in the ice of the Northwest Passage",
];
